apiVersion: velero.io/v1
kind: Backup
metadata:
  name: backup1
  labels:
    velero.io/storage-location: default
  namespace: openshift-adp
spec:
  includedNamespaces:
  - jon
  storageLocation: default
  ttl: 720h0m0s
  snapshotMoveData: true
