apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
spec:
  volumeMode: Filesystem
  storageClassName: ocs-external-storagecluster-ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: registry.redhat.io/rhel9/postgresql-15@sha256:802c7926383f9e4b31ac48dd42e5b7cce920c8ef09920abe2724e50a84fbea0b
          name: db
          env:
          - name: POSTGRESQL_USER
            value: todouser
          - name: POSTGRESQL_PASSWORD
            value: todopassword
          - name: POSTGRESQL_ADMIN_PASSWORD
            value: adminpassword
          - name: POSTGRESQL_DATABASE
            value: todos
          ports:
          - containerPort: 5432
            name: theport
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/pgsql/data
      restartPolicy: Always
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db

---

apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  ports:
    - name: port5432
      port: 5432
      targetPort: 5432
  selector:
    app: db
  type: ClusterIP
